name: Anex Tour News

on:
  schedule:
    - cron: '0 6 * * *'     # каждый день в 9:00 по Москве
  workflow_dispatch:        # можно запускать вручную

jobs:
  send-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run newsletter
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ vars.TELEGRAM_CHAT_ID }}   # добавим позже
        run: python news.py
